### ISSUE TITLE
twMerge remove shadow color without reason

### ISSUE THREAD

**Issue by viktorbonino** [dcastil/tailwind-merge#277] opened 2023-08-07 16:17 UTC
### Describe the bug

If you have both a shadow (shadow-lg for example) and a shadow color (shadow-red-500 for example) it removes the shadow color class even if it's not necessary.

**Comment by dcastil** [comment] 2023-08-07 17:15
Hey @viktorbonino! 👋

Do you have a way to reproduce the issue you have? I just tried it out with https://codesandbox.io/s/tailwind-merge-playground-cssr35?file=/src/index.ts and

```ts
const mergeData: MergeData[] = [
    {
        args: ['shadow-lg shadow-red-500'],
    },
]
```

but the result was `shadow-lg shadow-red-500` as expected.

**Comment by viktorbonino** [comment] 2023-08-07 17:57
I have this problem using tailwind-variants (that uses twMerge under the hood), so at this point it could be a tailwind-variants bug.

**Comment by dcastil** [comment] 2023-08-08 11:20
Ah, then you need to pass the tailwind-merge config to tailwind-variants which then passes that config to tailwind-merge. Here is the place where you need to pass the tailwind-merge config: https://www.tailwind-variants.org/docs/api-reference#twmergeconfig

Here is an example on how to configure tailwind-merge: https://github.com/dcastil/tailwind-merge/blob/v1.14.0/docs/recipes.md#adding-custom-scale-from-tailwind-config-to-tailwind-merge-config.

And here is the documentation on how the tailwind-merge configuration works: https://github.com/dcastil/tailwind-merge/blob/v1.14.0/docs/configuration.md#usage-with-custom-tailwind-config.

Related: https://github.com/dcastil/tailwind-merge/issues/276, https://github.com/dcastil/tailwind-merge/discussions/275, https://github.com/dcastil/tailwind-merge/issues/274, https://github.com/dcastil/tailwind-merge/issues/250, https://github.com/dcastil/tailwind-merge/issues/207

**Comment by fredericoo** [comment] 2023-09-02 18:02
For some reason I’m also having this in my project using `shadcn-ui`. Im’ on `"tailwind-merge": "^1.14.0"` and using a custom shadow + colour, with no custom config on tailwind-merge

**Comment by tom-ads** [comment] 2023-09-24 19:14
Having the same issue with version `^1.13.2`. I have a custom shadow `"focus-md": "0px 0px 0px 3px rgba(0, 0, 0, 0.3)"` and when using `className="shadow-focus-md shadow-grey-200"` the custom shadow colour isn't being applied. Removing the twMerge call works as expected.

**Comment by williamli** [comment] 2023-09-25 15:56
@tom-ads I just figured this out.

```
// tailwind.config.js

module.exports = {
  theme: {
    extend: {
      boxShadow: {
        highlight: 'inset 1.5rem -0.75rem 0.5rem 0.1rem'
      },
    }
  }
}

```

I need to use `extendTailwindMerge` to tell `tailwind-merge` that I have added an extra shadow class because [it doesn't support that key](https://github.com/dcastil/tailwind-merge/blob/v1.14.0/docs/configuration.md#theme) by default.

```
import { extendTailwindMerge } from 'tailwind-merge';

export default function Component({ className }: { className?: string }) {

  const twMerge = extendTailwindMerge({
    classGroups: {
      shadow: [{ shadow: ['highlight'] }]
    }
  })


  return <a href="#" className={twMerge("shadow-highlight shadow-red-500", className)}>Hello</a>

}
```

**Comment by G9000** [comment] 2023-10-25 04:33
<img width="571" alt="Screenshot 2023-10-05 at 5 46 17 PM" src="https://github.com/dcastil/tailwind-merge/assets/11317652/3bd3a89b-89e4-4bbb-82d3-e6c97591ed06">
<img width="202" alt="Screenshot 2023-10-05 at 5 54 09 PM" src="https://github.com/dcastil/tailwind-merge/assets/11317652/d8fa7a09-18c7-4e43-a79b-413b0d85fe79">

does not seem to work or im missing something. For context im not extending anything but replacing the original tailwind colors classes.

**Comment by G9000** [comment] 2023-10-25 04:34
<img width="370" alt="Screenshot 2023-10-25 at 12 32 18 PM" src="https://github.com/dcastil/tailwind-merge/assets/11317652/b7ed373f-3151-4515-8f12-0e98d3d9b07f">

<img width="481" alt="Screenshot 2023-10-25 at 12 32 29 PM" src="https://github.com/dcastil/tailwind-merge/assets/11317652/5bf33dd2-1c37-4286-a620-ad7a81057c12">
Hmm did i do anything wrong? Does not seem to work. For context, I replace the tailwind colors not extending it.

**Comment by G9000** [comment] 2023-10-25 04:36
<img width="370" alt="Screenshot 2023-10-25 at 12 32 18 PM" src="https://github.com/dcastil/tailwind-merge/assets/11317652/b7dfc2a4-03ba-4c88-8b87-e97e2d899ccf">
<img width="481" alt="Screenshot 2023-10-25 at 12 32 29 PM" src="https://github.com/dcastil/tailwind-merge/assets/11317652/f11a36b2-6a03-4492-bc43-5102144177ff">


Does not seem to work on my end. For context i replace the colors not extending it.

**Comment by dcastil** [comment] 2023-10-28 20:51
@G9000 you generally don't need to configure colors in tailwind-merge. tailwind-merge will detect all classes that look like color classes and are not known to tailwind-merge as color classes.

```ts
twMerge('text-my-custom-red text-xl text-another-custom-color') === 'text-xl text-another-custom-color'
```

**Comment by Sliov** [comment] 2024-03-12 05:42
Same here with arbitrary values: ```shadow-[inset_0_1px_0,inset_0_-1px_0] shadow-[hsl(var(--border-primary))]```

**Comment by dcastil** [comment] 2024-03-15 11:25
@Sliov your case is indeed a bug. I created a new issue for it in https://github.com/dcastil/tailwind-merge/issues/391 and am going to close this one to keep things organized.

For the others: In case your issue is not resolved yet, please let me know and I'll reopen this again.

**Closed by dcastil** 2024-03-15 11:25 UTC
Labels: context-v1
