### ISSUE TITLE
Text size overwrites text color

### ISSUE THREAD

**Issue by donald-richardson-dxd** [dcastil/tailwind-merge#202] opened 2023-02-17 08:03 UTC
If I apply twMerge to the following I lose text-red-500

`text-red-500 text-sm`

**Comment by dcastil** [comment] 2023-02-17 08:24
Hey @donald-richardson-dxd! 👋

I just tested this in https://codesandbox.io/s/tailwind-merge-playground-cssr35?file=/src/index.ts and couldn't reproduce it. Are you sure that the issue isn't somewhere else?

**Comment by donald-richardson-dxd** [comment] 2023-02-17 17:35
I think I found the issue. I have a non tailwind class on the element called `text-input-error-message` which is erasing `text-red-500`.

**Comment by dcastil** [comment] 2023-02-17 17:52
Ah yeah, tailwind-merge identifies anything it doesn't recognize starting with `text-` as a color. You could fix this by adding a prefix to that class, e.g. `n-text-input-error-message`.

**Comment by dcastil** [comment] 2023-02-23 13:16
@binaryartifex The reason for this is that [in the default config](https://github.com/dcastil/tailwind-merge/blob/v1.10.0/src/lib/default-config.ts#L583) the [validator](https://github.com/dcastil/tailwind-merge/blob/v1.10.0/docs/api-reference.md#validators) `isTshirtSize` is used. That one only allows the strings `xs`, `sm`, `md`, `lg`, `xl` with an optional number in front of it. You could rewrite your `xxs` class to `2xs` to make it work or add the `xxs` size to the tailwind-merge config. [Here](https://github.com/dcastil/tailwind-merge/blob/v1.10.0/docs/recipes.md#adding-custom-scale-from-tailwind-config-to-tailwind-merge-config) is a guide for that.

**Comment by binaryartifex** [comment] 2023-02-23 22:29
ahh yep i see. didn't even register to use the tailwind merge config. helps to read the docs. ill give myself a self prescribed uppercut. cheers mate.

**Comment by dcastil** [comment] 2023-02-24 10:49
Haha no worries. 😁

@donald-richardson-dxd I'm closing this as resolved. Let me know in case your issue isn't resolved yet.

**Closed by dcastil** 2023-02-24 10:49 UTC
