### ISSUE TITLE
'default' is not exported by dependency 'hashlru'

### ISSUE THREAD

**Issue by bobthered** [dcastil/tailwind-merge#92] opened 2022-04-22 13:21 UTC
I'm utilizing tailwind-merge in a [sveltekit](https://kit.svelte.dev/docs/introduction) app and receiving an error associated with the  dependency [hashlru](https://github.com/dominictarr/hashlru) in dev & when building.  It appears tailwind-merge is using ES6 imports, but hashlru is using CJS and throwing an error due to missing the default export.

```
'default' is not exported by node_modules/hashlru/index.js, imported by node_modules/tailwind-merge/dist/lib/lru-cache.mjs
```

**Comment by dcastil** [comment] 2022-04-22 19:01
Hey @bobthered! 👋 

Do you have a minimal reproduction of this? I just tried out the SvelteKit demo app from https://kit.svelte.dev/docs/introduction#getting-started and it didn't cause any issues.

![Screenshot 2022-04-22 at 20 58 34](https://user-images.githubusercontent.com/31006608/164777571-9b7672c2-0418-4a7d-b603-fee3d06b0a07.png)

![Screenshot 2022-04-22 at 20 58 04](https://user-images.githubusercontent.com/31006608/164777542-734d092b-fd3a-47f8-998b-33d00860700f.png)

**Comment by bobthered** [comment] 2022-04-25 12:09
I added you to a private repo [bobthered/tailwind-merge-test](https://github.com/bobthered/tailwind-merge-test).  I'm using the npm package [sveltewind](https://github.com/sveltewind/sveltewind).  When I run the dev server, I get the hashlru error.

**Comment by dcastil** [comment] 2022-04-25 16:55
Thanks for the repro.

I just checked it and I saw that the `hashlru` package wasn't transformed to ESM properly. There is still the `module.exports` call in the browser request which the browser won't understand (it's using CommonJS exports instead of ESM which are only meant for Node.js).

![Screenshot 2022-04-25 at 18 37 30](https://user-images.githubusercontent.com/31006608/165134394-2be5e27c-5f4c-42ed-ab0b-a177bd79ee23.png)

Usually Vite transforms CommonJS module to ESM, e.g. here is how tailwind-merge is transformed from CommonJS to ESM in my own Vite app:

![Screenshot 2022-04-25 at 18 42 04](https://user-images.githubusercontent.com/31006608/165135021-d1dad6c4-0d82-4d2e-8faa-80177cf80d9b.png)

I'm not sure where exactly the problem is, but seems that Sveltekit changed the Vite config so that it won't transform CommonJS modules. But I found a hint in the SvelteKit FAQ: https://kit.svelte.dev/faq#packages

> It is encouraged to make sure the dependencies of external Svelte components provide an ESM version. However, in order to handle CommonJS dependencies [vite-plugin-svelte will look for any CJS dependencies of external Svelte components](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#what-is-going-on-with-vite-and-pre-bundling-dependencies) and ask Vite to pre-bundle them by automatically adding them to Vite's optimizeDeps.include which will use esbuild to convert them to ESM. A side effect of this approach is that it takes longer to load the initial page. If this becomes noticable, try setting [experimental.prebundleSvelteLibraries: true](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#prebundlesveltelibraries) in svelte.config.js. Note that this option is experimental.

This behavior seems to come from SvelteKit. Maybe it makes sense to open an issue there?

I'm closing the issue here as it seems that there isn't anything wrong in tailwind-merge itself. Hope this could still help you. 🙏 Feel free to tell me if you think there is indeed a bug in tailwind-merge and I'll reopen this issue.

**Closed by dcastil** 2022-04-25 16:55 UTC
Labels: bug

**Comment by bobthered** [comment] 2022-04-25 17:38
Thanks for the info.  After debugging, I added the hashlru dependency to the optimizeDeps.include config for vite and that seemed to fix it.  I updated the repo as well FYI.  Thanks again.
